import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const version = String(pkg.version || "0.0.0");

const versionJs = `/** Generated by npm run sync-version — do not edit by hand. */
export const APP_VERSION = "${version}";
export const CACHE_BUST = "${version}";
`;

fs.writeFileSync(path.join(root, "www/version.js"), versionJs);

for (const rel of ["www/index.html", "www/app.js"]) {
  const p = path.join(root, rel);
  let s = fs.readFileSync(p, "utf8");
  s = s.replace(/\?v=[0-9.]+/g, `?v=${version}`);
  fs.writeFileSync(p, s);
}

console.log(`synced version ${version}`);
